translated 05-06-01
m-takagi/php-the-right-way pull request #23
Opened 2023-08-18 16:01 UTC by tkaneda

05-06-01 の国際化、ローカライズのページが未訳だったので、訳してみました。

2023-08-26 10:04 UTC, mumumu reviewed
何点かコメントしました。これらに対応頂ければ、マージできると思います。

尚、マージした後であっても、下記の点は後から修正すると思います。
これらは、議論し始めるとキリがないためです。

- 既存の文体である「だ、である調」に従っていない点
- 見出し (## や ### で始まる行) の後の改行が中途半端な点

2023-08-26 10:04 UTC, mumumu commented on _posts/05-06-01-Internationalization-and-Localization.md
> +- [php-gettext/Gettext][php-gettext]: OOインタフェースでのGettextサポート。改良されたヘルパー関数、いくつかのファイルフォーマットのための強力な抽出器（`gettext` コマンドによるネイティブにサポートしないものもある）を含み、`.mo/.po` ファイル以外の他のフォーマットにエクスポートすることもできる。翻訳ファイルをJavaScriptイン
```suggestion
- [php-gettext/Gettext][php-gettext]: OOインタフェースでのGettextサポート。改良されたヘルパー関数、いくつかのファイルフォーマットのための強力な抽出器（`gettext` コマンドがネイティブにサポートしないものもある）を含み、`.mo/.po` ファイル以外の他のフォーマットにエクスポートすることもできる。翻訳ファイルをJavaScriptインターフェースなどのシステムの他の部分に統合する必要がある場合に役に立つ。
```

2023-08-26 10:04 UTC, mumumu commented on _posts/05-06-01-Internationalization-and-Localization.md
> +ここでは、[Poedit] を使って翻訳ファイルを作成する。おそらくシステムのパッケージマネージャにもあると思う。Unix, macOS, Windows で使うことができ、[poedit_download] [ウェブサイトから無料でダウンロード] することができる。
```suggestion
ここでは、[Poedit] を使って翻訳ファイルを作成する。おそらくシステムのパッケージマネージャにもあると思う。Unix, macOS, Windows で使うことができ、[poedit_download] [ウェブサイトから無料でダウンロード] することもできる。
```

2023-08-26 10:04 UTC, mumumu commented on _posts/05-06-01-Internationalization-and-Localization.md
> +gettext を使う際、通常扱うファイルは３つある。主たるファイルは PO(Portable Object) ファイルと、MO(Machine Object) ファイルで、１つ目は読み取り可能な「翻訳されたオブジェクト」のリストであり、２つ目は、ローカライズを行う際に、gettext によって解釈される対応するバイナリだ。また他に、POT (Template) ファイルがあり、これはソースファ
```suggestion
gettext を使う際、通常扱うファイルは３つある。主なファイルは PO(Portable Object) ファイルと、MO(Machine Object) ファイルで、１つ目は読み取り可能な「翻訳されたオブジェクト」のリストであり、２つ目は、ローカライズを行う際に、gettext によって解釈される対応するバイナリだ。また他に、POT (Template) ファイルがあり、これはソースファイルからの既存のキーを全て含んでいて、すべてのPOファイルを生成、更新するためのガイドとして利用することができる。これらのテンプレートファイルは必須ではなく、l10n を行う際に用いるツールによっては、PO/MO ファイルだけで事足りる。言語と地域ごとにPO/MO ファイルのペアが常に１つあるが、POTはドメインごとに１つだけだ。
```

2023-08-26 10:04 UTC, mumumu commented on _posts/05-06-01-Internationalization-and-Localization.md
> +一部の話者にとっては、国のぶぶんが冗長に思える場合がある。実際、言語の中には、オーストリアドイツ語(`de_AT`) や ブラジルポルトガル語(`pt_BR`) のように、異なる国の方言を持つものがある。２つ目の部分は、これらの方言を区別するために使われる。２つ目の部分がない場合、言語の「汎用」バージョン、あるいは「ハイブリッド」バージョンとして扱われる。
```suggestion
一部の話者にとっては、国の部分が冗長に思える場合がある。実際、言語の中には、オーストリアドイツ語(`de_AT`) や ブラジルポルトガル語(`pt_BR`) のように、異なる国の方言を持つものがある。２つ目の部分は、これらの方言を区別するために使われる。２つ目の部分がない場合、言語の「汎用」バージョン、あるいは「ハイブリッド」バージョンとして扱われる。
```

2023-08-26 10:04 UTC, mumumu commented on _posts/05-06-01-Internationalization-and-Localization.md
> +理論面が一通り終わったら、少し実用的なことを扱おう。ここに、`.po` ファイルの抜粋がある。フォーマットについては気にしないでいただきたいが、代わりに全体的な内容をお示しする。後で簡単に編集する方法を学ぼう。
```suggestion
理論面が一通り終わったら、少し実用的なことを扱おう。ここに、`.po` ファイルの抜粋がある。フォーマットについては気にしないでいただきたいが、代わりに全体的な内容を示す。後で簡単に編集する方法を学ぼう。
```

2023-08-26 10:04 UTC, mumumu commented on _posts/05-06-01-Internationalization-and-Localization.md
> +２つ目のセクションは単純な文字列を英語からブラジルポルトガル語へ翻訳し、３つ目のセクションも同じことを行っているが、[`sprintf`][sprintf]からの文字列置換を使って、翻訳にユーザメイト訪問日が含まれるようにする。
```suggestion
２つ目のセクションは単純な文字列を英語から(ブラジルで話される)ポルトガル語へ翻訳し、３つ目のセクションも同じことを行っているが、[`sprintf`][sprintf]からの文字列置換を使って、翻訳にユーザメイト訪問日が含まれるようにする。
```

2023-08-26 10:04 UTC, mumumu commented on _posts/05-06-01-Internationalization-and-Localization.md
> +２つ目のセクションは単純な文字列を英語からブラジルポルトガル語へ翻訳し、３つ目のセクションも同じことを行っているが、[`sprintf`][sprintf]からの文字列置換を使って、翻訳にユーザメイト訪問日が含まれるようにする。
↑いわゆる[ブラポル語](https://ja.wikipedia.org/wiki/%E3%83%96%E3%83%A9%E3%82%B8%E3%83%AB%E3%83%9D%E3%83%AB%E3%83%88%E3%82%AC%E3%83%AB%E8%AA%9E) ですが、このくらいの方がわかりやすいでしょう、という意図で提案しています。

2023-08-26 10:04 UTC, mumumu commented on _posts/05-06-01-Internationalization-and-Localization.md
> +### 毎日の用法
```suggestion
### お決まりの使い方
```

2023-08-26 10:04 UTC, mumumu commented on _posts/05-06-01-Internationalization-and-Localization.md
> +Gettext が独自のフレームワークの i18n パッケージに対して持っている大きな利点の１つは、広範で強力なファイルフォーマットだ。「ああ、それを理解し、手で編集することは非常に困難だ。単純な配列の方が簡単だ！」間違いなく、[Poedit] のようなアプリケーションが_大いに_助けになる。[彼らのウェブサイト][poedit_download]からプログラムを入手することができ、すべてのプラ
```suggestion
Gettext が独自のフレームワークの i18n パッケージに対して持っている大きな利点の１つは、広範で強力なファイルフォーマットだ。「ああ、Gettext のフォーマットを理解し、手で編集することは非常に困難だ。単純な配列の方が簡単だ！」間違いなく、[Poedit] のようなアプリケーションが_大いに_助けになる。[彼らのウェブサイト][poedit_download]からプログラムを入手することができ、すべてのプラットフォームで無料で利用することができる。これは、使い慣れるのにかなり簡単なツールであり、同時に非常に強力なツールである。Gettextが利用できるすべての機能を使う。このガイドはPoEdit 1.8 に基づいている。
```

2023-08-26 10:04 UTC, mumumu commented on _posts/05-06-01-Internationalization-and-Localization.md
> +次に、先に説明したディレクトリ構造を使ってァイルを保存する。さらに、「Extract from sources」をクリックし、ここで抽出タスクと翻訳タスクの様々な設定を行う。「Catalog > Properties」で後からこれらすべてを見つけることができるようになる。
```suggestion
次に、先に説明したディレクトリ構造を使ってファイルを保存する。さらに、「Extract from sources」をクリックし、ここで抽出タスクと翻訳タスクの様々な設定を行う。「Catalog > Properties」で後からこれらすべてを見つけることができるようになる。
```

2023-08-26 10:04 UTC, mumumu commented on _posts/05-06-01-Internationalization-and-Localization.md
> +すでにお気づきかもしれないが、ローカライズされた文字列には、２つの主要なタイプがある。単数のものとそを複数形にしたものだ。１つ目は、ソースとローカライズされた文字列の２つのボックスがあるだけだ。Gettext/Poedit にはソースファイルを変更する権限がないので、ソース文字列は変更ができない。ソース自体を変更して、再スキャンする必要がある。ヒント：翻訳行を右クリックすると、その文字列が使われ
```suggestion
すでにお気づきかもしれないが、ローカライズされた文字列には、２つの主なタイプがある。単数のものとそれを複数形にしたものだ。１つ目は、ソースとローカライズされた文字列の２つのボックスがあるだけだ。Gettext/Poedit にはソースファイルを変更する権限がないので、ソース文字列は変更ができない。ソース自体を変更して、再スキャンする必要がある。ヒント：翻訳行を右クリックすると、その文字列が使われているソースファイルと行のヒントが表示される。
```

2023-08-26 10:04 UTC, mumumu commented on _posts/05-06-01-Internationalization-and-Localization.md
> +最後に、「View > Untranslated entries first」マークをつけておくことをお勧めする。これは、エントリを忘れないようにするのに_大いに_役に立つからだ。このメニューから、必要に応じて、翻訳者たちにコンテキスト情報を残すことができるUI をオープンすることもできる。
```suggestion
最後に、「View > Untranslated entries first」マークをつけておくことをお勧めする。これは、エントリを忘れないようにするのに_大いに_役に立つからだ。このメニューから、必要に応じて、翻訳者たちにコンテキスト情報を残すことができる UI をオープンすることもできる。
```

2023-08-26 10:04 UTC, mumumu commented on _posts/05-06-01-Internationalization-and-Localization.md
> +[dn_func]: https://www.php.net/manual/function.dngettext.php [日本語版](https://www.php.net/manual/ja/function.dngettext.php)
PHP マニュアルについては、わざわざ「日本語版」のリンクを示さずとも、普段使っているロケールのページにリダイレクトしてくれます。なので、上記の付け足しは不要なはずです。

2023-08-28 13:24 UTC, tkaneda commented
ありがとうございます。修正入れます。

2023-08-29 15:29 UTC, mumumu requested changes
原文をプレビューしてもう一度読み直し、さらに気付いた点をコメントしました。修正をお願いします。

2023-08-29 15:29 UTC, mumumu commented on _posts/05-06-01-Internationalization-and-Localization.md
>  1. _`msgid` as a real sentence_.
上記の一文は不要です。

2023-08-29 15:29 UTC, mumumu commented on _posts/05-06-01-Internationalization-and-Localization.md
> +2. _一意な構造化されたキーとしての `msgid` _
```suggestion
2. _一意な構造化されたキーとしての `msgid`_
```

上記のスペースを入れると、斜体としてレンダリングされなくなります。

2023-08-29 15:29 UTC, mumumu commented on _posts/05-06-01-Internationalization-and-Localization.md
> +大きなプロジェクトでは、同じ単語がコンテキストに応じて異なる意味を伝える場合、翻訳を分離する必要がある場合がある。そのような場合、それらを別の_ドメイン_に分割する。それらは基本的に、POT/PO/MOファイルの名前付きグループであり、その場合のファイル名は前述の_翻訳ドメイン_である。中小規模のプロジェクトでは通常、単純化するために、１つのドメインのみを使用する。その名前は任意だが、我々のコー
```suggestion
大きなプロジェクトでは、同じ単語がコンテキストに応じて異なる意味を伝える場合、翻訳を分離する必要がある場合がある。そのような場合、それらを別の _ドメイン_ に分割する。それらは基本的に、POT/PO/MOファイルの名前付きグループであり、その場合のファイル名は前述の _翻訳ドメイン_ である。中小規模のプロジェクトでは通常、単純化するために、１つのドメインのみを使用する。その名前は任意だが、我々のコードサンプルでは「main」を使う。[Symfony] プロジェクトでは、例えば、ドメインはバリデーションメッセージの翻訳を分離するために利用される。
```

`_` で囲む単語の前後には、細かくて申し訳ないのですがスペースが必要です。markdown でのレンダリングの都合上、細かくて申し訳ないですが修正お願いします。

また、 `main` は、bindtextdomain の引数として書かれています。なので訳してはいけません。

2023-08-29 15:29 UTC, mumumu commented on _posts/05-06-01-Internationalization-and-Localization.md
> +２つ目のセクションは単純な文字列を英語から(ブラジルで話される)ポルトガル語へ翻訳し、３つ目のセクションも同じことを行っているが、[`sprintf`][sprintf]からの文字列置換を使って、翻訳にユーザメイト訪問日が含まれるようにする。
```suggestion
２つ目のセクションは単純な文字列を英語から(ブラジルで話される)ポルトガル語へ翻訳し、３つ目のセクションも同じことを行っているが、[`sprintf`][sprintf]からの文字列置換を使って、翻訳にユーザ名と訪問日が含まれるようにする。
```

2023-08-29 15:29 UTC, mumumu commented on _posts/05-06-01-Internationalization-and-Localization.md
> +翻訳キーに関していえば、ここには２つの主要な「スクール」がある。
```suggestion
翻訳キーに関していえば、ここには２つの主要な「流派」がある。
```

2023-08-29 15:29 UTC, mumumu commented on _posts/05-06-01-Internationalization-and-Localization.md
> +#### 2. サンプルセットアップファイル(上記で用いた `i18n_setup.php`)、正しいロケールの選択や、Gettext の設定
```suggestion
#### 2. サンプルセットアップファイル(上記で用いた `i18n_setup.php`)、正しいロケールの選択や、Gettext の設定を行う
```

2023-08-29 15:29 UTC, mumumu commented on _posts/05-06-01-Internationalization-and-Localization.md
> +Gettext が独自のフレームワークの i18n パッケージに対して持っている大きな利点の１つは、広範で強力なファイルフォーマットだ。「ああ、Gettext のフォーマットを理解し、手で編集することは非常に困難だ。単純な配列の方が簡単だ！」間違いなく、[Poedit] のようなアプリケーションが_大いに_助けになる。[彼らのウェブサイト][poedit_download]からプログラムを入手す
```suggestion
Gettext が独自のフレームワークの i18n パッケージに対して持っている大きな利点の１つは、広範で強力なファイルフォーマットだ。「ああ、Gettext のフォーマットを理解し、手で編集することは非常に困難だ。単純な配列の方が簡単だ！」間違いなく、[Poedit] のようなアプリケーションが _大いに_ 助けになる。[彼らのウェブサイト][poedit_download]からプログラムを入手することができ、すべてのプラットフォームで無料で利用することができる。これは、使い慣れるのにかなり簡単なツールであり、同時に非常に強力なツールである。Gettextが利用できるすべての機能を使う。このガイドはPoEdit 1.8 に基づいている。
```

2023-08-29 15:29 UTC, mumumu commented on _posts/05-06-01-Internationalization-and-Localization.md
> +* [PHP Manual: Gettext](https://www.php.net/manual/book.gettext.php) [日本語版](https://www.php.net/manual/ja/book.gettext.php)
PHP マニュアルについては、わざわざ「日本語版」のリンクを示さずとも、普段使っているロケールのページにリダイレクトしてくれます。なので、上記の付け足しは不要なはずです。

2023-08-30 14:24 UTC, tkaneda commented
詳細にレビューいただき、ありがとうございました。ご指摘いただいた部分、修正しました。
お手数おかけしました。

2023-09-01 15:56 UTC, mumumu approved these changes
まだ不完全な部分はありますが、いったんマージします。ありがとうございました。

2023-09-01 15:56 UTC, merged